package define

const (
	ANOTHEREXAMPLE_TEST1 = 999999
	ANOTHEREXAMPLE_TEST2 = 999998
	ANOTHEREXAMPLE_TEST3 = 999997
	ANOTHEREXAMPLE_ERR = 999996
)


const (
	HEARTBREATING_INIT = iota
	HEARTBREATING_NORMAL 
	HEARTBREATING_TIMEOUT
	CRC_INIT
	CRC_NORMAL
	CRC_UPSIDEDOWN
	CRC_NOTPASS
	STAMPS_INIT
)
